apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c91knf310-go 
  janus-idp.io/tekton: c91knf310-go
  backstage.io/kubernetes-id: c91knf310-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c91knf310-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  