apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c91knf310-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c91knf310-go 
  name: c91knf310-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c91knf310-go 
